### ISSUE TITLE
Radio knop op afstandsbediening werkt niet

### ISSUE THREAD

**Issue by NovapaX** [NovapaX/sparqltv#1]
Melding Tweak:
De radio-knop op de afstandsbediening werkt nog niet, u kunt via het 'menu' naar radio navigeren.

**Comment by ElmerLastdrager** [comment]
Werkt hier prima. Opgelost dus?

**Comment by NovapaX** [comment]
Heb heb het hier ook even gecontroleerd en werkt inderdaad.
(gebruik hier zelf tegenwoordig een harmony en een aparte reciever, radiofunctie van sparql werd dus niet meer gebruikt)
